"""add assignment_type, assignments

Revision ID: 0edf79c2855c
Revises: 90447e905ba8
Create Date: 2024-10-02 22:00:54.112257

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0edf79c2855c"
down_revision = "90447e905ba8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assignment_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("standard_artifact")
    op.drop_table("artifact")
    op.drop_table("user_artifacts")
    with op.batch_alter_table("assignment", schema=None) as batch_op:
        batch_op.add_column(sa.Column("assignmenttype_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_assignment_assignment_type_id",
            "assignment_type",
            ["assignmenttype_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assignment", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("assignmenttype_id")

    op.create_table(
        "user_artifacts",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.Column("artifact_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["artifact_id"], ["artifact.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "artifact",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=64), nullable=True),
        sa.Column("link", sa.VARCHAR(length=128), nullable=True),
        sa.Column("narrative", sa.VARCHAR(length=1000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "standard_artifact",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("standard_id", sa.INTEGER(), nullable=True),
        sa.Column("artifact_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["artifact_id"], ["artifact.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["standard_id"], ["standard.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("assignment_type")
    # ### end Alembic commands ###
