"""add standard_type

Revision ID: 1b28118198ed
Revises: 49080fd6e3e0
Create Date: 2025-07-05 14:42:19.604519

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1b28118198ed"
down_revision = "49080fd6e3e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("standard", schema=None) as batch_op:
        batch_op.add_column(sa.Column("standardtype_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_standard_type_standardtype_id",
            "standard_type",
            ["standardtype_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("standard", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("standardtype_id")

    # ### end Alembic commands ###
