"""Active flag on standards

Revision ID: 23f55f0ef3ed
Revises: 496aee67d671
Create Date: 2024-02-18 14:40:48.514855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f55f0ef3ed'
down_revision = '496aee67d671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standard', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
