"""add proficiency associations

Revision ID: 49080fd6e3e0
Revises: d70da2802924
Create Date: 2024-12-19 20:00:56.797393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49080fd6e3e0'
down_revision = 'd70da2802924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_standards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('standard_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['standard_id'], ['standard.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_standards')
    # ### end Alembic commands ###
