"""Add active bool to user

Revision ID: 496aee67d671
Revises: 691ac7fa28fa
Create Date: 2024-02-16 15:23:25.283985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496aee67d671'
down_revision = '691ac7fa28fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
