"""require unique email

Revision ID: 538fb3e93697
Revises: f0e215237b75
Create Date: 2023-08-25 12:16:20.499952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538fb3e93697'
down_revision = 'f0e215237b75'
branch_labels = None
depends_on = None

convention={
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None, naming_convention=convention) as batch_op:
        batch_op.create_unique_constraint('uq_users_emails', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
