"""assignment title on attempt record

Revision ID: 691ac7fa28fa
Revises: 538fb3e93697
Create Date: 2023-08-29 21:53:36.253929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691ac7fa28fa'
down_revision = '538fb3e93697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standard_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standard_attempt', schema=None) as batch_op:
        batch_op.drop_column('assignment')

    # ### end Alembic commands ###
