"""assignment foreign key on standard attempt

Revision ID: 90447e905ba8
Revises: 23f55f0ef3ed
Create Date: 2024-03-22 22:12:40.108946

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90447e905ba8"
down_revision = "23f55f0ef3ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("standard_attempt", schema=None) as batch_op:
        batch_op.add_column(sa.Column("assignment_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_assignment_id_assignment_id_id", "assignment", ["assignment_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("standard_attempt", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("assignment_id")

    # ### end Alembic commands ###
