"""display name for standards

Revision ID: b5bb7d12e37d
Revises: c53ae6518533
Create Date: 2025-09-02 21:03:15.515842

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b5bb7d12e37d"
down_revision = "c53ae6518533"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("standard", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("display_name", sa.String(length=12), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("standard", schema=None) as batch_op:
        batch_op.drop_column("display_name")

    # ### end Alembic commands ###
